# Generated by Django 4.2.1 on 2023-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_dougnuttopping_filling_remove_item_size_size_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='isCake',
            new_name='cake',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='isChops',
            new_name='pastery',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='isSnakes',
            new_name='savoury',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dTopping',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filling',
        ),
        migrations.RemoveField(
            model_name='item',
            name='flavours',
        ),
        migrations.RemoveField(
            model_name='item',
            name='icing',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='DougnutTopping',
        ),
        migrations.DeleteModel(
            name='Flavour',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
