# Generated by Django 4.2.1 on 2023-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_glaze_remove_flavour_size_rename_iscake_item_cake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dummuy',
            field=models.BooleanField(null=True),
        ),
    ]
