# Generated by Django 4.2.1 on 2023-05-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_item_dummuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dummuy',
        ),
    ]
