# Generated by Django 4.2.1 on 2023-06-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pastery',
        ),
        migrations.RemoveField(
            model_name='item',
            name='savoury',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('cake', 'CAKE'), ('finger-food', 'FINGER FOOD'), ('pasteries', 'PASTERRIES'), ('cookies', 'COOKIES'), ('cupcakes', 'CUPCAKES')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='filling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
