# Generated by Django 4.2.1 on 2023-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_remove_item_cake_remove_item_pastery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('CC', 'cake'), ('FF', 'finger-food'), ('PT', 'pasteries'), ('CK', 'cookies'), ('CP', 'cupcakes')], max_length=12, null=True),
        ),
    ]
