# Generated by Django 4.2.1 on 2023-06-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('cake', 'cake'), ('finger-food', 'finger food'), ('pasteries', 'pasteries'), ('cookies', 'cookies'), ('cupcakes', 'cupcakes')], max_length=12, null=True),
        ),
    ]
