# Generated by Django 4.2.1 on 2023-06-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_alter_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('green', 'green'), ('pink', 'pink'), ('purple', 'purple'), ('orange', 'orange'), ('white', 'white'), ('black', 'black'), ('vanilla', 'vanilla')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('inscription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('cookies', 'cookies'), ('fingerfood', 'fingerfood'), ('cupcakes', 'cupcakes'), ('pasteries', 'pasteries')], max_length=500)),
                ('pieces', models.CharField(choices=[('6', '6'), ('10', '10'), ('30', '30'), ('50', '50'), ('100', '100')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Filling',
        ),
        migrations.DeleteModel(
            name='Glaze',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RenameField(
            model_name='icing',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='icing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='cake',
            name='icing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.icing'),
        ),
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sizes'),
        ),
        migrations.AddField(
            model_name='cake',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='config.topping'),
        ),
    ]
