# Generated by Django 4.2.1 on 2023-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_cake_products_sizes_delete_filling_delete_glaze_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Glaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sprinkles', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='pieces',
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('cookies', 'cookies'), ('fingerfood', 'fingerfood'), ('cupcakes', 'cupcakes'), ('pasteries', 'pasteries'), ('cakes', 'cakes')], max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
