# Generated by Django 4.2.1 on 2023-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_filling_glaze_remove_products_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaze',
            name='sprinkles',
            field=models.BooleanField(null=True),
        ),
    ]
