# Generated by Django 4.2.1 on 2023-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_remove_glaze_sprinkles'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
