# Generated by Django 4.2.1 on 2023-06-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_rename_type_products_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
    ]
