# Generated by Django 4.2.1 on 2023-06-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_alter_products_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_type',
            new_name='type',
        ),
    ]
