# Generated by Django 4.2.1 on 2023-06-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_remove_products_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
