# Generated by Django 4.2.1 on 2023-06-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('config', '0030_remove_cartitem_item_cartitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.cartitem'),
        ),
    ]
