# Generated by Django 4.2.1 on 2023-07-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.cart'),
        ),
    ]
