# Generated by Django 4.2.1 on 2023-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_remove_cartitem_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, to='config.cart'),
        ),
    ]
