# Generated by Django 4.2.1 on 2023-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_remove_cartitem_cart_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ManyToManyField(blank=True, to='config.cartitem'),
        ),
    ]
