# Generated by Django 4.2.1 on 2023-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_remove_cart_cartitem_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(max_length=300)),
                ('lga', models.JSONField(null=True)),
            ],
        ),
    ]
