# Generated by Django 4.2.1 on 2023-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_states_delete_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='lazyImage',
            field=models.ImageField(blank=True, default='images/placeholder-1-1.webp', null=True, upload_to='images'),
        ),
    ]
