# Generated by Django 4.2.1 on 2024-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_products_lazyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_ordered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
