# Generated by Django 4.2.1 on 2024-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping',
            new_name='price',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
