# Generated by Django 4.2.1 on 2024-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_rename_shipping_shippingaddress_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
