# Generated by Django 4.2.1 on 2024-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_alter_shippingaddress_deliverydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
