# Generated by Django 4.2.1 on 2024-06-13 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_alter_filling_price_alter_glaze_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/placeholder-1-1.webp', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
