# Generated by Django 4.2.1 on 2024-07-14 05:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0053_rename_glaze_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='product_name',
        ),
        migrations.AddField(
            model_name='producttype',
            name='bannerIimage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='bannerText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='routeProtection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
