# Generated by Django 4.2.1 on 2024-07-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0054_remove_producttype_banner_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='bannerIimage',
            new_name='bannerImage',
        ),
    ]
