# Generated by Django 4.2.1 on 2024-07-15 08:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_rename_banneriimage_producttype_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='bannerText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
