# Generated by Django 4.2.1 on 2024-07-15 09:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_alter_producttype_bannertext_alter_producttype_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='bannerImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bannerImage'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='lazyImage'),
        ),
    ]
