# Generated by Django 4.2.1 on 2024-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0057_alter_producttype_bannerimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='lazyImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images'),
        ),
    ]
