# Generated by Django 4.2.1 on 2024-07-20 05:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_customeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='bannerImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bannerImage'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='lazyImage'),
        ),
    ]
