# Generated by Django 4.2.1 on 2024-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_alter_products_image_alter_products_lazyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='cartTotal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
