# Generated by Django 4.2.1 on 2024-08-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0062_shippingaddress_carttotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cartTotal',
        ),
        migrations.AddField(
            model_name='icing',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sizes',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filling',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filling',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='icing',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='icing',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.filling')),
                ('icing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.icing')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.layer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.products')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.sizes')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.topping')),
            ],
        ),
    ]
