# Generated by Django 4.2.1 on 2024-08-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_remove_shippingaddress_carttotal_icing_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='filling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.filling'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='icing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.icing'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.layer'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.products'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.sizes'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.topping'),
        ),
    ]
