# Generated by Django 5.1 on 2024-09-25 19:25

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0065_alter_cart_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('parameter', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='icing',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.collection'),
        ),
    ]
