# Generated by Django 5.1 on 2024-09-26 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0066_collection_icing_image_products_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='parameter',
            new_name='alt',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='price',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
