# Generated by Django 5.1 on 2024-09-30 10:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0067_rename_parameter_collection_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='collection',
            name='lazyImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
